CREATE DATABASE BT_BUOI1test2
ON
(
	NAME = 'BT_BUOI1test2',
	FILENAME = 'D:\Learn\SQL_server\BT_BUOI1test2.mdf',
	SIZE = 2 MB,
	MAXSIZE = UNLIMITED,
	FILEGROWTH = 10%
)
GO
USE BT_BUOI1test2
GO

CREATE TABLE Khoa
(
	--tên khoa không trùng thêm unique
	MaK CHAR(10) PRIMARY KEY NOT NULL,
	TenKhoa NVARCHAR(20) UNIQUE NOT NULL,
	SDT TEXT NOT NULL,
	DiaChi TEXT NOT NULL
)
GO

CREATE TABLE Lop
(
	MaLop CHAR(10) PRIMARY KEY NOT NULL,
	TenLop NVARCHAR(20) UNIQUE NOT NULL,

	MaK CHAR(10) NOT NULL,
	FOREIGN KEY (MaK) REFERENCES dbo.Khoa(MaK)
)
GO

CREATE TABLE SinhVien
(
	MaSV CHAR(10) PRIMARY KEY NOT NULL,
	TenSV NVARCHAR(20) NOT NULL,
	GioiTinh BIT NOT NULL,
	--kiểm tra sinh viên trên 18 tuổi
	NgaySinh DATE CHECK ((YEAR(GETDATE()) - YEAR(NgaySinh)) >= 18)  NOT NUlL,

	MaLop CHAR(10) NOT NULL,
	FOREIGN KEY (MaLop) REFERENCES dbo.Lop(MaLop)
)
GO

CREATE TABLE Mon
(
	MaN CHAR(10) PRIMARY KEY NOT NULL,
	TenM NVARCHAR(20) NOT NULL,
	SoTC INT CHECK(SoTC <= 5) NOT NUlL
)
GO

CREATE TABLE Diem
(
	MaSV CHAR(10) NOT NULL,
	MaMon CHAR(10) NOT NULL,
	NgayHoc DATE NOT NULL,
	DiemCC FLOAT NOT NUlL,
	DiemGiuaKi FLOAT NOT NULL,
	DiemThi FLOAT CHECK(DiemThi Between 0 and 10) NOT NULL
)	
GO

ALTER TABLE Diem
ADD CONSTRAINT Diem_PK PRIMARY KEY (MaSV, MaMon, NgayHoc);